[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r app/backend/requirements.txt"]

[phases.build]
cmds = ["cd app/backend"]

[start]
cmd = "cd app/backend && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT"

